--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 15.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: match_documents(public.vector, integer, jsonb); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.match_documents(query_embedding public.vector, match_count integer DEFAULT 5, filter jsonb DEFAULT '{}'::jsonb) RETURNS TABLE(id bigint, record_manager_id text, content text, metadata jsonb, similarity double precision)
    LANGUAGE plpgsql
    AS $$
begin
  return query
  select
    documents.id,
    documents.record_manager_id,
    documents.content,
    documents.metadata,
    1 - (documents.embedding <=> query_embedding) as similarity
  from documents
  where documents.metadata @> filter
  order by documents.embedding <=> query_embedding
  limit match_count;
end;
$$;


--
-- Name: rls_auto_enable(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.rls_auto_enable() RETURNS event_trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'pg_catalog'
    AS $$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: data_pbk_peserta_2026; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.data_pbk_peserta_2026 (
    id bigint NOT NULL,
    record_manager_id bigint,
    nama_lengkap text,
    jenis_kelamin text,
    pendidikan_terakhir text,
    nama_lpk_penyelenggara text,
    bidang text,
    rentang_umur text,
    provinsi_peserta text,
    kabupaten_kota_peserta text,
    pekerjaan text,
    skema text,
    tanggal_uji date,
    tempat_uji_kompetensi text,
    kabupaten_kota_penyelenggaraan text,
    provinsi_penyelenggaraan text,
    k_bk boolean,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: data_pbk_pemandu_wisata_tirta_2026_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.data_pbk_peserta_2026 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.data_pbk_pemandu_wisata_tirta_2026_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: data_pbk_peserta_2025; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.data_pbk_peserta_2025 (
    id bigint NOT NULL,
    record_manager_id bigint,
    nama_lengkap text,
    jenis_kelamin text,
    pendidikan_terakhir text,
    nama_lpk_penyelenggara text,
    bidang text,
    rentang_umur text,
    provinsi_peserta text,
    kabupaten_kota_peserta text,
    pekerjaan text,
    skema text,
    tanggal_uji text,
    tempat_uji_kompetensi text,
    kabupaten_kota_penyelenggaraan text,
    provinsi_penyelenggaraan text,
    k_bk boolean,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: data_pbk_peserta_2025_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.data_pbk_peserta_2025 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.data_pbk_peserta_2025_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: data_sertifikasi_pariwisata_2025; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.data_sertifikasi_pariwisata_2025 (
    id bigint NOT NULL,
    record_manager_id bigint,
    nama_lengkap text,
    jenis_kelamin text,
    pendidikan_terakhir text,
    nama_lsp_penyelenggara text,
    skema text,
    rentang_umur text,
    provinsi_peserta text,
    kabupaten_kota_peserta text,
    pekerjaan text,
    bidang text,
    tanggal_uji date,
    tuk text,
    kabupaten_kota_penyelenggaraan text,
    provinsi_penyelenggaraan text,
    k_bk boolean,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: data_sertifikasi_pariwisata_2025_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.data_sertifikasi_pariwisata_2025 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.data_sertifikasi_pariwisata_2025_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documents (
    id bigint NOT NULL,
    record_manager_id text,
    content text,
    embedding public.vector(768),
    metadata jsonb,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: documents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: documents_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.documents_id_seq OWNED BY public.documents.id;


--
-- Name: record_manager; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.record_manager (
    id bigint NOT NULL,
    source_id text NOT NULL,
    file_name text NOT NULL,
    source_folder text DEFAULT 'unknown'::text NOT NULL,
    data_type text NOT NULL,
    column_names text,
    content_hash text NOT NULL,
    category text,
    file_summary text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    table_name text,
    "Confidence" text,
    CONSTRAINT record_manager_data_type_check CHECK ((data_type = ANY (ARRAY['text'::text, 'tabular'::text])))
);


--
-- Name: record_manager_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.record_manager_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: record_manager_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.record_manager_id_seq OWNED BY public.record_manager.id;


--
-- Name: ref_data; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ref_data (
    id text NOT NULL,
    nama text,
    path text,
    jenis text,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: ref_file; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ref_file (
    id text NOT NULL,
    nama text,
    path text,
    jenis text
);


--
-- Name: ref_kkni_daftar_pariwisata_2024; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ref_kkni_daftar_pariwisata_2024 (
    id bigint NOT NULL,
    record_manager_id bigint,
    judul_kkni text,
    nomor_kkni text,
    bidang text,
    subbidang text,
    tahun_penetapan integer,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: ref_kkni_daftar_pariwisata_2024_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ref_kkni_daftar_pariwisata_2024 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ref_kkni_daftar_pariwisata_2024_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ref_lpk_blk_pariwisata_2025; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ref_lpk_blk_pariwisata_2025 (
    id bigint NOT NULL,
    record_manager_id bigint,
    nama_lpk_blk text,
    wilayah text,
    provinsi text,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: ref_lpk_blk_pariwisata_2025_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ref_lpk_blk_pariwisata_2025 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ref_lpk_blk_pariwisata_2025_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ref_lsp_pariwisata_2025; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ref_lsp_pariwisata_2025 (
    id bigint NOT NULL,
    record_manager_id bigint,
    nama_lsp text,
    wilayah text,
    provinsi text,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: ref_lsp_pariwisata_2025_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ref_lsp_pariwisata_2025 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ref_lsp_pariwisata_2025_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ref_modul_pbk_2025; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ref_modul_pbk_2025 (
    id bigint NOT NULL,
    record_manager_id bigint,
    judul_modul text,
    kode_unit text,
    tahun_penerbitan integer,
    skkni_terkait text,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: ref_modul_pbk_2025_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ref_modul_pbk_2025 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ref_modul_pbk_2025_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ref_skkni_pariwisata_2025; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ref_skkni_pariwisata_2025 (
    id bigint NOT NULL,
    record_manager_id bigint,
    nama_skkni text,
    nomor_skkni text,
    bidang text,
    subbidang text,
    tahun_penetapan integer,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: ref_skkni_pariwisata_2025_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ref_skkni_pariwisata_2025 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ref_skkni_pariwisata_2025_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ref_trash; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ref_trash (
    id text NOT NULL,
    nama text,
    path text,
    jenis text
);


--
-- Name: documents id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents ALTER COLUMN id SET DEFAULT nextval('public.documents_id_seq'::regclass);


--
-- Name: record_manager id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.record_manager ALTER COLUMN id SET DEFAULT nextval('public.record_manager_id_seq'::regclass);


--
-- Name: data_pbk_peserta_2026 data_pbk_pemandu_wisata_tirta_2026_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_pbk_peserta_2026
    ADD CONSTRAINT data_pbk_pemandu_wisata_tirta_2026_pkey PRIMARY KEY (id);


--
-- Name: data_pbk_peserta_2025 data_pbk_peserta_2025_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_pbk_peserta_2025
    ADD CONSTRAINT data_pbk_peserta_2025_pkey PRIMARY KEY (id);


--
-- Name: data_sertifikasi_pariwisata_2025 data_sertifikasi_pariwisata_2025_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_sertifikasi_pariwisata_2025
    ADD CONSTRAINT data_sertifikasi_pariwisata_2025_pkey PRIMARY KEY (id);


--
-- Name: documents documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (id);


--
-- Name: record_manager record_manager_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.record_manager
    ADD CONSTRAINT record_manager_pkey PRIMARY KEY (id);


--
-- Name: record_manager record_manager_source_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.record_manager
    ADD CONSTRAINT record_manager_source_id_key UNIQUE (source_id);


--
-- Name: ref_data ref_data_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ref_data
    ADD CONSTRAINT ref_data_pkey PRIMARY KEY (id);


--
-- Name: ref_file ref_file_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ref_file
    ADD CONSTRAINT ref_file_pkey PRIMARY KEY (id);


--
-- Name: ref_kkni_daftar_pariwisata_2024 ref_kkni_daftar_pariwisata_2024_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ref_kkni_daftar_pariwisata_2024
    ADD CONSTRAINT ref_kkni_daftar_pariwisata_2024_pkey PRIMARY KEY (id);


--
-- Name: ref_lpk_blk_pariwisata_2025 ref_lpk_blk_pariwisata_2025_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ref_lpk_blk_pariwisata_2025
    ADD CONSTRAINT ref_lpk_blk_pariwisata_2025_pkey PRIMARY KEY (id);


--
-- Name: ref_lsp_pariwisata_2025 ref_lsp_pariwisata_2025_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ref_lsp_pariwisata_2025
    ADD CONSTRAINT ref_lsp_pariwisata_2025_pkey PRIMARY KEY (id);


--
-- Name: ref_modul_pbk_2025 ref_modul_pbk_2025_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ref_modul_pbk_2025
    ADD CONSTRAINT ref_modul_pbk_2025_pkey PRIMARY KEY (id);


--
-- Name: ref_skkni_pariwisata_2025 ref_skkni_pariwisata_2025_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ref_skkni_pariwisata_2025
    ADD CONSTRAINT ref_skkni_pariwisata_2025_pkey PRIMARY KEY (id);


--
-- Name: ref_trash ref_trash_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ref_trash
    ADD CONSTRAINT ref_trash_pkey PRIMARY KEY (id);


--
-- Name: idx_data_pbk_pemandu_wisata_tirta_2026_k_bk; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_data_pbk_pemandu_wisata_tirta_2026_k_bk ON public.data_pbk_peserta_2026 USING btree (k_bk);


--
-- Name: idx_data_pbk_pemandu_wisata_tirta_2026_record_manager_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_data_pbk_pemandu_wisata_tirta_2026_record_manager_id ON public.data_pbk_peserta_2026 USING btree (record_manager_id);


--
-- Name: idx_data_pbk_pemandu_wisata_tirta_2026_tanggal_uji; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_data_pbk_pemandu_wisata_tirta_2026_tanggal_uji ON public.data_pbk_peserta_2026 USING btree (tanggal_uji);


--
-- Name: idx_data_pbk_peserta_2025_k_bk; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_data_pbk_peserta_2025_k_bk ON public.data_pbk_peserta_2025 USING btree (k_bk);


--
-- Name: idx_data_pbk_peserta_2025_record_manager_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_data_pbk_peserta_2025_record_manager_id ON public.data_pbk_peserta_2025 USING btree (record_manager_id);


--
-- Name: idx_data_sertifikasi_pariwisata_2025_k_bk; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_data_sertifikasi_pariwisata_2025_k_bk ON public.data_sertifikasi_pariwisata_2025 USING btree (k_bk);


--
-- Name: idx_data_sertifikasi_pariwisata_2025_record_manager_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_data_sertifikasi_pariwisata_2025_record_manager_id ON public.data_sertifikasi_pariwisata_2025 USING btree (record_manager_id);


--
-- Name: idx_data_sertifikasi_pariwisata_2025_tanggal_uji; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_data_sertifikasi_pariwisata_2025_tanggal_uji ON public.data_sertifikasi_pariwisata_2025 USING btree (tanggal_uji);


--
-- Name: idx_ref_kkni_daftar_pariwisata_2024_record_manager_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ref_kkni_daftar_pariwisata_2024_record_manager_id ON public.ref_kkni_daftar_pariwisata_2024 USING btree (record_manager_id);


--
-- Name: idx_ref_kkni_daftar_pariwisata_2024_tahun_penetapan; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ref_kkni_daftar_pariwisata_2024_tahun_penetapan ON public.ref_kkni_daftar_pariwisata_2024 USING btree (tahun_penetapan);


--
-- Name: idx_ref_lpk_blk_pariwisata_2025_record_manager_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ref_lpk_blk_pariwisata_2025_record_manager_id ON public.ref_lpk_blk_pariwisata_2025 USING btree (record_manager_id);


--
-- Name: idx_ref_lsp_pariwisata_2025_record_manager_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ref_lsp_pariwisata_2025_record_manager_id ON public.ref_lsp_pariwisata_2025 USING btree (record_manager_id);


--
-- Name: idx_ref_modul_pbk_2025_record_manager_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ref_modul_pbk_2025_record_manager_id ON public.ref_modul_pbk_2025 USING btree (record_manager_id);


--
-- Name: idx_ref_modul_pbk_2025_tahun_penerbitan; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ref_modul_pbk_2025_tahun_penerbitan ON public.ref_modul_pbk_2025 USING btree (tahun_penerbitan);


--
-- Name: idx_ref_skkni_pariwisata_2025_record_manager_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ref_skkni_pariwisata_2025_record_manager_id ON public.ref_skkni_pariwisata_2025 USING btree (record_manager_id);


--
-- Name: idx_ref_skkni_pariwisata_2025_tahun_penetapan; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ref_skkni_pariwisata_2025_tahun_penetapan ON public.ref_skkni_pariwisata_2025 USING btree (tahun_penetapan);


--
-- Name: data_pbk_peserta_2026 data_pbk_pemandu_wisata_tirta_2026_record_manager_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_pbk_peserta_2026
    ADD CONSTRAINT data_pbk_pemandu_wisata_tirta_2026_record_manager_id_fkey FOREIGN KEY (record_manager_id) REFERENCES public.record_manager(id) ON DELETE CASCADE;


--
-- Name: data_pbk_peserta_2025 data_pbk_peserta_2025_record_manager_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_pbk_peserta_2025
    ADD CONSTRAINT data_pbk_peserta_2025_record_manager_id_fkey FOREIGN KEY (record_manager_id) REFERENCES public.record_manager(id) ON DELETE CASCADE;


--
-- Name: data_sertifikasi_pariwisata_2025 data_sertifikasi_pariwisata_2025_record_manager_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_sertifikasi_pariwisata_2025
    ADD CONSTRAINT data_sertifikasi_pariwisata_2025_record_manager_id_fkey FOREIGN KEY (record_manager_id) REFERENCES public.record_manager(id) ON DELETE CASCADE;


--
-- Name: ref_kkni_daftar_pariwisata_2024 ref_kkni_daftar_pariwisata_2024_record_manager_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ref_kkni_daftar_pariwisata_2024
    ADD CONSTRAINT ref_kkni_daftar_pariwisata_2024_record_manager_id_fkey FOREIGN KEY (record_manager_id) REFERENCES public.record_manager(id) ON DELETE CASCADE;


--
-- Name: ref_lpk_blk_pariwisata_2025 ref_lpk_blk_pariwisata_2025_record_manager_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ref_lpk_blk_pariwisata_2025
    ADD CONSTRAINT ref_lpk_blk_pariwisata_2025_record_manager_id_fkey FOREIGN KEY (record_manager_id) REFERENCES public.record_manager(id) ON DELETE CASCADE;


--
-- Name: ref_lsp_pariwisata_2025 ref_lsp_pariwisata_2025_record_manager_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ref_lsp_pariwisata_2025
    ADD CONSTRAINT ref_lsp_pariwisata_2025_record_manager_id_fkey FOREIGN KEY (record_manager_id) REFERENCES public.record_manager(id) ON DELETE CASCADE;


--
-- Name: ref_modul_pbk_2025 ref_modul_pbk_2025_record_manager_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ref_modul_pbk_2025
    ADD CONSTRAINT ref_modul_pbk_2025_record_manager_id_fkey FOREIGN KEY (record_manager_id) REFERENCES public.record_manager(id) ON DELETE CASCADE;


--
-- Name: ref_skkni_pariwisata_2025 ref_skkni_pariwisata_2025_record_manager_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ref_skkni_pariwisata_2025
    ADD CONSTRAINT ref_skkni_pariwisata_2025_record_manager_id_fkey FOREIGN KEY (record_manager_id) REFERENCES public.record_manager(id) ON DELETE CASCADE;


--
-- Name: data_pbk_peserta_2025; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.data_pbk_peserta_2025 ENABLE ROW LEVEL SECURITY;

--
-- Name: data_pbk_peserta_2026; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.data_pbk_peserta_2026 ENABLE ROW LEVEL SECURITY;

--
-- Name: data_sertifikasi_pariwisata_2025; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.data_sertifikasi_pariwisata_2025 ENABLE ROW LEVEL SECURITY;

--
-- Name: documents; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;

--
-- Name: record_manager; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.record_manager ENABLE ROW LEVEL SECURITY;

--
-- Name: ref_data; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ref_data ENABLE ROW LEVEL SECURITY;

--
-- Name: ref_file; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ref_file ENABLE ROW LEVEL SECURITY;

--
-- Name: ref_kkni_daftar_pariwisata_2024; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ref_kkni_daftar_pariwisata_2024 ENABLE ROW LEVEL SECURITY;

--
-- Name: ref_lpk_blk_pariwisata_2025; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ref_lpk_blk_pariwisata_2025 ENABLE ROW LEVEL SECURITY;

--
-- Name: ref_lsp_pariwisata_2025; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ref_lsp_pariwisata_2025 ENABLE ROW LEVEL SECURITY;

--
-- Name: ref_modul_pbk_2025; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ref_modul_pbk_2025 ENABLE ROW LEVEL SECURITY;

--
-- Name: ref_skkni_pariwisata_2025; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ref_skkni_pariwisata_2025 ENABLE ROW LEVEL SECURITY;

--
-- Name: ref_trash; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ref_trash ENABLE ROW LEVEL SECURITY;

--
-- Name: record_manager service_role_all_record_manager; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY service_role_all_record_manager ON public.record_manager USING (true) WITH CHECK (true);


--
-- PostgreSQL database dump complete
--

